### ISSUE TITLE
มี error ตอนสร้าง ท่าเรืออะครับ

### ISSUE THREAD

**Issue by pickyfly** [iAmMutun/BanishedTranslationTH#2]

**Comment by iAmMutun** [comment]
ขอบคุณที่แจ้งเข้ามานะครับ เพราะไม่ได้เข้ามาแก้ไขกว่าสองปีแล้ว คงต้องรอรื้อฟื้นกันสักหน่อย อาจจะพร้อมอัพเดทเกมเวอร์ชันหน้า (1.0.7)

**Comment by iAmMutun** [comment]
อัพเดทล่าสุดแก้ไข issue นี้ออกมาแล้วนะครับ ดาวน์โหลดที่ https://github.com/iAmMutun/BanishedTranslationTH/releases/tag/v0.4

**Comment by pickyfly** [comment]
ขอบคุณมากนะครับ

2017-02-17 0:04 GMT+07:00 Theeramet Ratsameewijitpaisan <
notifications@github.com>:
